# Generated by Django 3.2.15 on 2023-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('imagePath', models.CharField(max_length=500, null=True)),
                ('slug_title', models.SlugField(null=True)),
            ],
        ),
    ]
